# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='puuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
